package nemoclaw

import (
	"fmt"
	"strings"

	"github.com/paupawsan/rakitsu/internal/config"
	"github.com/paupawsan/rakitsu/internal/export/shared"
)

func singleReadme(projectName, agentName string) string {
	return fmt.Sprintf(`# %s — %s

Generated by Rakitsu for deployment on NemoClaw + OpenShell.

## Files

- `+"`openclaw.json`"+` — Agent configuration (verified against OpenClaw)
- `+"`sandbox-policy.yaml`"+` — OpenShell security policy (verified on DGX Spark)
- `+"`AGENT.md`"+` — Agent system prompt

## Deploy on NemoClaw

NemoClaw uses its own bundled blueprint. You only need to bring the agent
config and policy, then let NemoClaw create the sandbox.

`+"```bash"+`
# 1. Install NemoClaw (first time only)
curl -fsSL https://www.nvidia.com/nemoclaw.sh | bash

# 2. Create a sandbox with the interactive wizard
nemoclaw onboard
# → pick a name (e.g., %s), select inference provider, accept policy presets

# 3. Upload the agent config into the sandbox
openshell sandbox upload %s openclaw.json /sandbox/.openclaw/openclaw.json

# 4. Apply the Rakitsu-generated policy
openshell policy set sandbox-policy.yaml

# 5. Connect and run
nemoclaw %s connect
openclaw tui

# Or run programmatically (non-interactive):
# openclaw agent --agent main --local -m "your prompt here"
`+"```"+`

### Automation (non-interactive)

`+"```bash"+`
NEMOCLAW_SANDBOX_NAME=%s nemoclaw onboard --non-interactive
openshell sandbox upload %s openclaw.json /sandbox/.openclaw/openclaw.json
openshell policy set sandbox-policy.yaml
`+"```"+`

## Deploy on OpenClaw Only (no sandbox)

For local dev without OpenShell:

`+"```bash"+`
docker run -d -p 127.0.0.1:18789:18789 \
  -v $PWD/openclaw.json:/home/node/.openclaw/openclaw.json \
  ghcr.io/openclaw/openclaw:latest
`+"```"+`

## Environment Variables

Set your provider API keys before deploying:

`+"```bash"+`
export OPENAI_API_KEY="..."
export ANTHROPIC_API_KEY="..."
`+"```"+`
`, projectName, agentName,
		shared.SanitizeID(agentName), shared.SanitizeID(agentName), shared.SanitizeID(agentName),
		shared.SanitizeID(agentName), shared.SanitizeID(agentName))
}

func multiReadme(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# %s — NemoClaw Deployment\n\n", cfg.Name))
	sb.WriteString("Generated by Rakitsu. Multi-agent config exported with orchestration glue.\n\n")

	// Quick start
	sb.WriteString("## Quick Start\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("# Run with OpenShell/NemoClaw (requires pre-created sandboxes)\n")
	sb.WriteString("./orchestrate.sh openshell\n\n")
	sb.WriteString("# Run with Docker Compose (local dev)\n")
	sb.WriteString("docker compose up -d\n")
	sb.WriteString("./orchestrate.sh compose\n")
	sb.WriteString("```\n\n")

	// Files
	sb.WriteString("## Files\n\n")
	sb.WriteString("| File | Purpose |\n")
	sb.WriteString("|------|---------|\n")
	sb.WriteString("| `orchestrate.sh` | Runnable orchestration script |\n")
	sb.WriteString("| `docker-compose.yaml` | Local dev setup (one container per agent) |\n")

	strategy := ""
	if cfg.Orchestrator != nil {
		strategy = cfg.Orchestrator.Strategy
	}
	if strategy != "Pipeline" {
		sb.WriteString("| `delegate.sh` | Supervisor → worker delegation tool |\n")
	}
	for _, agent := range cfg.Agents {
		sb.WriteString(fmt.Sprintf("| `agent-%s/` | %s (%s) |\n", shared.SanitizeID(agent.Name), agent.Name, agent.Role))
	}
	sb.WriteString("\n")

	// Orchestration description
	if cfg.Orchestrator != nil {
		sb.WriteString(fmt.Sprintf("## Orchestration: %s\n\n", strategy))

		if cfg.Orchestrator.Pipeline != nil && len(cfg.Orchestrator.Pipeline.Steps) > 0 {
			for i, step := range cfg.Orchestrator.Pipeline.Steps {
				agent := step.Agent
				if agent == "" {
					agent = step.Name
				}
				stepType := step.Type
				if stepType == "" {
					stepType = "sequential"
				}
				sb.WriteString(fmt.Sprintf("%d. **%s** → `agent-%s/` (%s)\n", i+1, step.Name, shared.SanitizeID(agent), stepType))
			}
		} else {
			sb.WriteString("Supervisor delegates to workers dynamically:\n\n")
			for _, name := range cfg.Orchestrator.Agents {
				sb.WriteString(fmt.Sprintf("- **%s** (`agent-%s/`)\n", name, shared.SanitizeID(name)))
			}
		}
		sb.WriteString("\n")
	}

	// Security note
	sb.WriteString("## Security\n\n")
	sb.WriteString("- Agent outputs are passed as context to downstream agents via files.\n")
	sb.WriteString("  A compromised agent could inject malicious content into subsequent agents.\n")
	sb.WriteString("- Environment variables are passed through to containers (not embedded in files).\n")
	sb.WriteString("- Docker Compose uses an internal network with no published ports.\n")

	return sb.String()
}
