package core

import (
	"fmt"
	"strings"

	"github.com/paupawsan/rakitsu/internal/config"
	"github.com/paupawsan/rakitsu/internal/export/shared"
)

// GenerateOrchestration produces runnable orchestration artifacts for multi-agent
// exports: orchestrate.sh, docker-compose.yaml, and optionally delegate.sh.
// The orchestration logic (DAG, parallelism, synthesis, loops) is target-agnostic.
// RuntimeTargets provide the platform-specific run_agent() implementation.
func GenerateOrchestration(cfg *config.Config, outputDir string, targets []RuntimeTarget) error {
	strategy := ""
	if cfg.Orchestrator != nil {
		strategy = cfg.Orchestrator.Strategy
	}

	// Generate orchestrate.sh based on strategy
	var script string
	switch strategy {
	case "Pipeline":
		var err error
		script, err = GeneratePipelineScript(cfg, targets)
		if err != nil {
			return fmt.Errorf("generate pipeline script: %w", err)
		}
	default:
		// ReAct, Hierarchical, PlanAndExecute — all LLM-driven delegation
		script = GenerateReActScript(cfg, targets)
		// Generate delegate.sh for supervisor → worker calls
		delegateScript := GenerateDelegateScript(cfg, targets)
		if err := shared.WriteExecutable(fmt.Sprintf("%s/delegate.sh", outputDir), delegateScript); err != nil {
			return fmt.Errorf("write delegate.sh: %w", err)
		}
	}

	if err := shared.WriteExecutable(fmt.Sprintf("%s/orchestrate.sh", outputDir), script); err != nil {
		return fmt.Errorf("write orchestrate.sh: %w", err)
	}

	// Generate docker-compose.yaml for local testing
	compose := GenerateDockerCompose(cfg)
	if err := shared.WriteFile(fmt.Sprintf("%s/docker-compose.yaml", outputDir), compose); err != nil {
		return fmt.Errorf("write docker-compose.yaml: %w", err)
	}

	return nil
}

// DefaultTargetName returns the first target's name for use as default MODE.
func DefaultTargetName(targets []RuntimeTarget) string {
	if len(targets) > 0 {
		return targets[0].Name()
	}
	return "compose"
}

// SupervisorAgentName returns the display name used for the orchestrator's own
// "connect to supervisor" step in the generated ReAct/Hierarchical script.
// Callers that need a directory/service ID from this name must sanitize it
// themselves (shared.SanitizeID) — kept as one function so the script's
// "connect to X" text and any exported supervisor directory can't drift apart.
func SupervisorAgentName(cfg *config.Config) string {
	if cfg.Orchestrator != nil && cfg.Orchestrator.Name != "" {
		return cfg.Orchestrator.Name
	}
	return "supervisor"
}

// CollectAgentIDs extracts sanitized agent IDs from config.
func CollectAgentIDs(cfg *config.Config) []string {
	ids := make([]string, 0, len(cfg.Agents))
	for _, a := range cfg.Agents {
		ids = append(ids, shared.SanitizeID(a.Name))
	}
	return ids
}

// --- Pipeline script generation ---

// GeneratePipelineScript produces a bash script that runs pipeline steps in order,
// passing context between agents via files. Returns the script content and any error.
func GeneratePipelineScript(cfg *config.Config, targets []RuntimeTarget) (string, error) {
	if cfg.Orchestrator == nil || cfg.Orchestrator.Pipeline == nil {
		return "", fmt.Errorf("no pipeline config found")
	}

	steps := cfg.Orchestrator.Pipeline.Steps
	if err := validatePipelineStepsForExport(steps); err != nil {
		return "", err
	}
	levels, err := BuildStepLevels(steps)
	if err != nil {
		return "", fmt.Errorf("invalid pipeline DAG: %w", err)
	}

	agentIDs := CollectAgentIDs(cfg)
	var b strings.Builder

	// Header
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("set -euo pipefail\n")
	b.WriteString(fmt.Sprintf("# Generated by Rakitsu — do not edit manually\n"))
	b.WriteString(fmt.Sprintf("# Project: %s  |  Strategy: Pipeline  |  Agents: %d\n", shared.SanitizeComment(cfg.Name), len(cfg.Agents)))
	b.WriteString("#\n")
	b.WriteString("# SECURITY NOTE: Context files in $WORKSPACE are passed between agents.\n")
	b.WriteString("# A compromised agent could inject malicious content into downstream agents.\n")
	b.WriteString("# Review agent outputs before trusting them in production.\n\n")

	// Mode and workspace setup
	b.WriteString(fmt.Sprintf(`MODE="${1:-%s}"`, DefaultTargetName(targets)))
	b.WriteString("\n")
	b.WriteString(`WORKSPACE="${WORKSPACE:-$(mktemp -d)}"` + "\n")
	b.WriteString("umask 077\n")
	b.WriteString(`trap 'echo "[orchestrate] Cleaning up $WORKSPACE"; rm -rf "$WORKSPACE"' EXIT` + "\n")
	b.WriteString(`mkdir -p "$WORKSPACE"` + "\n\n")

	// Color helpers
	b.WriteString("# Color output (disable with NO_COLOR=1)\n")
	b.WriteString("if [ -z \"${NO_COLOR:-}\" ] && [ -t 1 ]; then\n")
	b.WriteString("  GREEN='\\033[0;32m'; BLUE='\\033[0;34m'; RED='\\033[0;31m'; NC='\\033[0m'\n")
	b.WriteString("else\n")
	b.WriteString("  GREEN=''; BLUE=''; RED=''; NC=''\n")
	b.WriteString("fi\n\n")

	// run_agent function — delegates to RuntimeTarget
	b.WriteString("run_agent() {\n")
	b.WriteString("  local name=$1\n")
	b.WriteString("  local input_file=$2\n")
	b.WriteString("  local output_file=$3\n")
	b.WriteString(`  printf "${BLUE}[orchestrate]${NC} Running agent: %s\\n" "$name" >&2` + "\n")
	b.WriteString("  case \"$MODE\" in\n")
	for _, t := range targets {
		b.WriteString(fmt.Sprintf("    %s)\n", t.Name()))
		b.WriteString(t.RunAgentCase() + "\n")
		b.WriteString("      ;;\n")
	}
	b.WriteString("    *) echo \"Unknown mode: $MODE\" >&2; exit 2 ;;\n")
	b.WriteString("  esac\n")
	b.WriteString(`  printf "${GREEN}[orchestrate]${NC} Agent %s complete\\n" "$name" >&2` + "\n")
	b.WriteString("}\n\n")

	// Target-specific setup
	b.WriteString("# Runtime setup\n")
	b.WriteString("case \"$MODE\" in\n")
	for _, t := range targets {
		setup := t.SetupCommands(agentIDs)
		if setup != "" {
			b.WriteString(fmt.Sprintf("  %s)\n", t.Name()))
			b.WriteString(setup + "\n")
			b.WriteString("    ;;\n")
		}
	}
	b.WriteString("esac\n\n")

	// Build step lookup for task/agent mapping
	stepMap := make(map[string]config.PipelineStep)
	for _, s := range steps {
		stepMap[s.Name] = s
	}

	// Generate execution levels
	for levelIdx, level := range levels {
		// Level comment
		var levelNames []string
		for _, s := range level {
			levelNames = append(levelNames, shared.SanitizeComment(s.Name))
		}
		if len(level) > 1 {
			b.WriteString(fmt.Sprintf("# Level %d: [%s] (parallel)\n", levelIdx, strings.Join(levelNames, ", ")))
		} else {
			depInfo := ""
			if len(level[0].DependsOn) > 0 {
				deps := make([]string, len(level[0].DependsOn))
				for i, d := range level[0].DependsOn {
					deps[i] = shared.SanitizeComment(d)
				}
				depInfo = fmt.Sprintf(" (depends on: %s)", strings.Join(deps, ", "))
			}
			b.WriteString(fmt.Sprintf("# Level %d: %s%s\n", levelIdx, shared.SanitizeComment(level[0].Name), depInfo))
		}

		for _, step := range level {
			agentID := shared.SanitizeID(step.Agent)
			if agentID == "" {
				continue
			}

			// Write task input file: original query + context from dependencies.
			// step.Task is arbitrary, config-controlled multi-line text — write it
			// via a single shell-quoted printf argument rather than a heredoc, so
			// no delimiter collision (a task line matching a fixed heredoc
			// terminator) can end the redirect early and let the remainder of the
			// text run as live shell commands.
			b.WriteString(fmt.Sprintf("\n# Prepare input for step: %s\n", shared.SanitizeComment(step.Name)))
			taskText := step.Task
			if taskText == "" {
				taskText = "Execute your task."
			}
			b.WriteString(fmt.Sprintf("printf '%%s\\n' %s > \"$WORKSPACE/task-%s.txt\"\n", shared.ShellQuote(taskText), shared.SanitizeID(step.Name)))

			// Append context from dependencies
			if len(step.DependsOn) > 0 {
				b.WriteString(fmt.Sprintf("{\n"))
				b.WriteString(fmt.Sprintf("  cat \"$WORKSPACE/task-%s.txt\"\n", shared.SanitizeID(step.Name)))
				b.WriteString(fmt.Sprintf("  echo ''\n"))
				b.WriteString(fmt.Sprintf("  echo '## Previous Results'\n"))
				for _, dep := range step.DependsOn {
					b.WriteString(fmt.Sprintf("  echo %s\n", shared.ShellQuote("### "+dep)))
					b.WriteString(fmt.Sprintf("  cat \"$WORKSPACE/output-%s.txt\" 2>/dev/null || echo '(no output)'\n", shared.SanitizeID(dep)))
					b.WriteString(fmt.Sprintf("  echo ''\n"))
				}
				b.WriteString(fmt.Sprintf("} > \"$WORKSPACE/input-%s.txt\"\n", shared.SanitizeID(step.Name)))
			} else {
				b.WriteString(fmt.Sprintf("cp \"$WORKSPACE/task-%s.txt\" \"$WORKSPACE/input-%s.txt\"\n", shared.SanitizeID(step.Name), shared.SanitizeID(step.Name)))
			}
		}

		// Execute steps in this level
		if len(level) == 1 {
			step := level[0]
			agentID := shared.SanitizeID(step.Agent)
			if agentID == "" {
				continue
			}
			stepID := shared.SanitizeID(step.Name)
			// stepID is kebab-case (dashes) — fine as a filename component, but
			// dashes aren't legal in a bash identifier, so a distinct
			// underscore form is used for the LOOP_ITER_/PID_ variable names.
			stepVar := strings.ReplaceAll(strings.ToUpper(stepID), "-", "_")

			if step.Type == "loop" {
				// Loop step: repeat until condition agent returns PASS
				maxIter := step.MaxIterations
				if maxIter <= 0 {
					maxIter = 5
				}
				condAgent := shared.SanitizeID(step.ConditionAgent)
				if condAgent == "" {
					condAgent = agentID // self-evaluate if no condition agent
				}

				b.WriteString(fmt.Sprintf("\n# Loop step: %s (max %d iterations)\n", shared.SanitizeComment(step.Name), maxIter))
				// Snapshot the loop's original input (task + any DependsOn
				// context, already assembled above) before the loop starts.
				// Each retry rebuilds input-<id>.txt from this snapshot, not
				// from the bare task file — otherwise DependsOn context is
				// silently lost starting on the second iteration.
				b.WriteString(fmt.Sprintf("cp \"$WORKSPACE/input-%s.txt\" \"$WORKSPACE/input-%s-base.txt\"\n", stepID, stepID))
				b.WriteString(fmt.Sprintf("LOOP_ITER_%s=0\n", stepVar))
				b.WriteString(fmt.Sprintf("while [ \"$LOOP_ITER_%s\" -lt %d ]; do\n", stepVar, maxIter))
				b.WriteString(fmt.Sprintf("  LOOP_ITER_%s=$((LOOP_ITER_%s + 1))\n", stepVar, stepVar))
				// step.Name is passed as its own shell-quoted printf argument
				// (runtime %s substitution) rather than spliced into the
				// double-quoted format string at generation time — a name
				// containing a double-quote would otherwise break out of it.
				b.WriteString(fmt.Sprintf("  printf \"${BLUE}[orchestrate]${NC} Loop %%s iteration $LOOP_ITER_%s/%d\\n\" %s >&2\n",
					stepVar, maxIter, shared.ShellQuote(step.Name)))
				b.WriteString(fmt.Sprintf("  run_agent %s \"$WORKSPACE/input-%s.txt\" \"$WORKSPACE/output-%s.txt\"\n",
					shared.ShellQuote(agentID), stepID, stepID))

				// Condition check. The default prompt asks for a single
				// PASS/FAIL word on its own first line (rather than free-text
				// with PASS/FAIL embedded) so the check below can match on
				// exact first-line content instead of a whole-file substring
				// search — a bare `grep -qi PASS` misreads a legitimate FAIL
				// response that merely contains the substring "PASS"
				// (e.g. "This does NOT PASS the bar", or "FAIL -- reasoning
				// quality did not pass review").
				condPrompt := step.ConditionPrompt
				if condPrompt == "" {
					condPrompt = "Review the output. Respond with a single word on the first line: PASS or FAIL. You may add feedback on subsequent lines if FAIL."
				}
				b.WriteString(fmt.Sprintf("  {\n"))
				b.WriteString(fmt.Sprintf("    echo %s\n", shared.ShellQuote(condPrompt)))
				b.WriteString(fmt.Sprintf("    echo ''\n"))
				b.WriteString(fmt.Sprintf("    echo '## Output to evaluate'\n"))
				b.WriteString(fmt.Sprintf("    cat \"$WORKSPACE/output-%s.txt\"\n", stepID))
				b.WriteString(fmt.Sprintf("  } > \"$WORKSPACE/condition-%s.txt\"\n", stepID))
				b.WriteString(fmt.Sprintf("  run_agent %s \"$WORKSPACE/condition-%s.txt\" \"$WORKSPACE/condition-result-%s.txt\"\n",
					shared.ShellQuote(condAgent), stepID, stepID))
				// A response that doesn't comply with the requested format
				// (no exact "PASS" on its own first line) is safely treated
				// as FAIL — it retries rather than silently accepting output
				// an ambiguous response never actually confirmed.
				b.WriteString(fmt.Sprintf("  if head -n1 \"$WORKSPACE/condition-result-%s.txt\" | grep -qiE '^[[:space:]]*PASS[[:space:]]*$'; then\n", stepID))
				b.WriteString(fmt.Sprintf("    printf \"${GREEN}[orchestrate]${NC} Loop %%s: PASS\\n\" %s >&2\n", shared.ShellQuote(step.Name)))
				b.WriteString("    break\n")
				b.WriteString("  fi\n")
				b.WriteString(fmt.Sprintf("  printf \"${BLUE}[orchestrate]${NC} Loop %%s: FAIL, retrying...\\n\" %s >&2\n", shared.ShellQuote(step.Name)))

				// Feed condition feedback back as input for next iteration,
				// rebuilt from the pre-loop snapshot (task + DependsOn
				// context) rather than the bare task file.
				b.WriteString(fmt.Sprintf("  {\n"))
				b.WriteString(fmt.Sprintf("    cat \"$WORKSPACE/input-%s-base.txt\"\n", stepID))
				b.WriteString(fmt.Sprintf("    echo ''\n"))
				b.WriteString(fmt.Sprintf("    echo '## Previous attempt feedback'\n"))
				b.WriteString(fmt.Sprintf("    cat \"$WORKSPACE/condition-result-%s.txt\"\n", stepID))
				b.WriteString(fmt.Sprintf("  } > \"$WORKSPACE/input-%s.txt\"\n", stepID))
				b.WriteString("done\n\n")
			} else {
				// Regular sequential step
				b.WriteString(fmt.Sprintf("run_agent %s \"$WORKSPACE/input-%s.txt\" \"$WORKSPACE/output-%s.txt\"\n\n",
					shared.ShellQuote(agentID), stepID, stepID))
			}
		} else {
			// Parallel execution
			b.WriteString("\n# Run in parallel\n")
			var pids []string
			for _, step := range level {
				agentID := shared.SanitizeID(step.Agent)
				if agentID == "" {
					continue
				}
				stepID := shared.SanitizeID(step.Name)
				stepVar := strings.ReplaceAll(strings.ToUpper(stepID), "-", "_")
				b.WriteString(fmt.Sprintf("run_agent %s \"$WORKSPACE/input-%s.txt\" \"$WORKSPACE/output-%s.txt\" &\n",
					shared.ShellQuote(agentID), stepID, stepID))
				pids = append(pids, fmt.Sprintf("PID_%s=$!", stepVar))
			}
			for _, pid := range pids {
				b.WriteString(pid + "\n")
			}
			b.WriteString("\n# Wait for all parallel steps\n")
			for _, step := range level {
				pidVar := fmt.Sprintf("PID_%s", strings.ReplaceAll(strings.ToUpper(shared.SanitizeID(step.Name)), "-", "_"))
				b.WriteString(fmt.Sprintf("wait \"$%s\" || { printf \"${RED}[orchestrate]${NC} Step %%s failed\\n\" %s >&2; exit 1; }\n",
					pidVar, shared.ShellQuote(step.Name)))
			}
			b.WriteString("\n")
		}
	}

	// Synthesis step
	if cfg.Orchestrator.Pipeline.Synthesis {
		b.WriteString("# Synthesis: combine all results\n")
		b.WriteString("{\n")
		if cfg.Orchestrator.Pipeline.SynthesisPrompt != "" {
			b.WriteString(fmt.Sprintf("  echo %s\n", shared.ShellQuote(cfg.Orchestrator.Pipeline.SynthesisPrompt)))
		} else {
			b.WriteString("  echo 'Synthesize the following results into a coherent summary:'\n")
		}
		b.WriteString("  echo ''\n")
		for _, step := range steps {
			b.WriteString(fmt.Sprintf("  echo %s\n", shared.ShellQuote("## "+step.Name)))
			b.WriteString(fmt.Sprintf("  cat \"$WORKSPACE/output-%s.txt\" 2>/dev/null || echo '(no output)'\n", shared.SanitizeID(step.Name)))
			b.WriteString("  echo ''\n")
		}
		// Use the first agent for synthesis (or orchestrator model if available).
		// GeneratePipelineScript is an exported function in a package that
		// ships as public library code — it must not assume a caller already
		// validated cfg.Agents (both current callers, the nemoclaw/openclaw
		// exporters, do check len(cfg.Agents) == 0 before ever reaching here,
		// but a direct caller of this package isn't guaranteed to).
		if len(cfg.Agents) == 0 {
			return "", fmt.Errorf("synthesis is enabled but no agents are defined")
		}
		synthAgent := shared.SanitizeID(cfg.Agents[0].Name)
		b.WriteString(fmt.Sprintf("} > \"$WORKSPACE/input-synthesis.txt\"\n"))
		b.WriteString(fmt.Sprintf("run_agent %s \"$WORKSPACE/input-synthesis.txt\" \"$WORKSPACE/output-synthesis.txt\"\n",
			shared.ShellQuote(synthAgent)))
		b.WriteString("printf \"${GREEN}[orchestrate]${NC} Synthesis complete\\n\" >&2\n")
		b.WriteString("cat \"$WORKSPACE/output-synthesis.txt\"\n")
	} else {
		// Output the DAG's actual sink step's result — not steps[len-1],
		// which is only the last step in YAML array order. BuildStepLevels
		// computes true topological levels independent of array position, so
		// a config can legitimately declare its real final/sink step earlier
		// in the array (using explicit depends_on to avoid the implicit-chain
		// injection for undeclared steps).
		sink, err := findSinkStep(steps)
		if err != nil {
			return "", err
		}
		b.WriteString(fmt.Sprintf("# Output final result\n"))
		b.WriteString(fmt.Sprintf("cat \"$WORKSPACE/output-%s.txt\"\n", shared.SanitizeID(sink.Name)))
	}

	// Target-specific teardown
	b.WriteString("\n# Runtime teardown\n")
	b.WriteString("case \"$MODE\" in\n")
	for _, t := range targets {
		td := t.TeardownCommands()
		if td != "" {
			b.WriteString(fmt.Sprintf("  %s)\n", t.Name()))
			b.WriteString(td + "\n")
			b.WriteString("    ;;\n")
		}
	}
	b.WriteString("esac\n")

	b.WriteString("\nprintf \"${GREEN}[orchestrate]${NC} Pipeline complete\\n\" >&2\n")

	return b.String(), nil
}

// --- ReAct/Hierarchical script generation ---

// GenerateReActScript produces a bash script that starts worker sandboxes
// then starts the supervisor (which uses delegate.sh to call workers).
func GenerateReActScript(cfg *config.Config, targets []RuntimeTarget) string {
	var b strings.Builder

	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("set -euo pipefail\n")

	strategy := "ReAct"
	if cfg.Orchestrator != nil {
		strategy = cfg.Orchestrator.Strategy
	}

	b.WriteString(fmt.Sprintf("# Generated by Rakitsu — do not edit manually\n"))
	b.WriteString(fmt.Sprintf("# Project: %s  |  Strategy: %s  |  Agents: %d\n", shared.SanitizeComment(cfg.Name), shared.SanitizeComment(strategy), len(cfg.Agents)))
	b.WriteString("#\n")
	b.WriteString("# The supervisor agent delegates to worker agents via delegate.sh.\n")
	b.WriteString("# delegate.sh reads task input from stdin to prevent shell injection.\n\n")

	b.WriteString(fmt.Sprintf(`MODE="${1:-%s}"`, DefaultTargetName(targets)))
	b.WriteString("\n")
	b.WriteString(`SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"` + "\n\n")

	// Color helpers
	b.WriteString("if [ -z \"${NO_COLOR:-}\" ] && [ -t 1 ]; then\n")
	b.WriteString("  GREEN='\\033[0;32m'; BLUE='\\033[0;34m'; NC='\\033[0m'\n")
	b.WriteString("else\n")
	b.WriteString("  GREEN=''; BLUE=''; NC=''\n")
	b.WriteString("fi\n\n")

	agentIDs := CollectAgentIDs(cfg)

	supervisorName := shared.SanitizeID(SupervisorAgentName(cfg))

	b.WriteString("case \"$MODE\" in\n")
	for _, t := range targets {
		b.WriteString(fmt.Sprintf("  %s)\n", t.Name()))
		setup := t.SetupCommands(agentIDs)
		if setup != "" {
			b.WriteString(setup + "\n")
		}
		b.WriteString(fmt.Sprintf(`    printf "${GREEN}[orchestrate]${NC} Connecting to supervisor: %s\n" >&2`+"\n", supervisorName))
		// Connect to supervisor — target-specific
		switch t.Name() {
		case "openshell":
			b.WriteString(fmt.Sprintf("    nemoclaw %s connect\n", supervisorName))
		case "compose":
			b.WriteString(fmt.Sprintf("    docker compose exec agent-%s openclaw tui\n", supervisorName))
		default:
			b.WriteString(fmt.Sprintf("    echo \"Connect to supervisor agent-%s on %s\" >&2\n", supervisorName, t.Name()))
		}
		b.WriteString("    ;;\n")
	}
	b.WriteString("  *) echo \"Unknown mode: $MODE\" >&2; exit 2 ;;\n")
	b.WriteString("esac\n")

	return b.String()
}

// GenerateDelegateScript produces delegate.sh — a tool script that the supervisor
// agent calls to delegate tasks to worker agents. Reads task from stdin to prevent
// shell injection via CLI arguments.
func GenerateDelegateScript(cfg *config.Config, targets []RuntimeTarget) string {
	var b strings.Builder

	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("set -euo pipefail\n")
	b.WriteString("# Delegate tool — called by supervisor to invoke worker agents\n")
	b.WriteString("# Reads task from stdin to prevent shell injection via arguments\n")
	b.WriteString("# Generated by Rakitsu — do not edit manually\n\n")

	b.WriteString("AGENT=\"${1:?Usage: delegate.sh <agent-name>}\"\n\n")

	// Validate agent name
	b.WriteString("# Validate agent name is alphanumeric+hyphen only\n")
	b.WriteString("if [[ ! \"$AGENT\" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then\n")
	b.WriteString("  echo \"ERROR: Invalid agent name: $AGENT\" >&2\n")
	b.WriteString("  exit 1\n")
	b.WriteString("fi\n\n")

	// Whitelist of known agents
	b.WriteString("# Known agents (generated from config)\n")
	b.WriteString("KNOWN_AGENTS=(\n")
	for _, agent := range cfg.Agents {
		b.WriteString(fmt.Sprintf("  %s\n", shared.ShellQuote(shared.SanitizeID(agent.Name))))
	}
	b.WriteString(")\n\n")

	b.WriteString("VALID=false\n")
	b.WriteString("for a in \"${KNOWN_AGENTS[@]}\"; do\n")
	b.WriteString("  if [ \"$a\" = \"$AGENT\" ]; then VALID=true; break; fi\n")
	b.WriteString("done\n")
	b.WriteString("if [ \"$VALID\" != true ]; then\n")
	b.WriteString("  echo \"ERROR: Unknown agent: $AGENT\" >&2\n")
	b.WriteString("  exit 1\n")
	b.WriteString("fi\n\n")

	// Detect mode and delegate — target-specific
	b.WriteString("# Delegate to target runtime\n")
	if len(targets) == 1 {
		// Single target — no mode detection needed
		b.WriteString(targets[0].DelegateCase() + "\n")
	} else {
		// Multi-target — detect by available commands
		for i, t := range targets {
			if i == 0 {
				b.WriteString(fmt.Sprintf("if command -v %s &>/dev/null; then\n", DetectCommand(t)))
			} else {
				b.WriteString(fmt.Sprintf("elif command -v %s &>/dev/null; then\n", DetectCommand(t)))
			}
			b.WriteString(t.DelegateCase() + "\n")
		}
		b.WriteString("else\n")
		b.WriteString("  echo \"ERROR: No supported runtime found\" >&2\n")
		b.WriteString("  exit 1\n")
		b.WriteString("fi\n")
	}

	return b.String()
}

// DetectCommand returns the command name to check for runtime detection.
func DetectCommand(t RuntimeTarget) string {
	switch t.Name() {
	case "openshell":
		return "openshell"
	case "compose":
		return "docker"
	default:
		return t.Name()
	}
}

// --- Docker Compose generation ---

// GenerateDockerCompose produces a docker-compose.yaml with one service per agent,
// a shared context volume, and env var passthrough (no secret values).
func GenerateDockerCompose(cfg *config.Config) string {
	var b strings.Builder

	b.WriteString("# Generated by Rakitsu — do not edit manually\n")
	b.WriteString("# Local development setup for multi-agent export\n")
	b.WriteString(fmt.Sprintf("# Project: %s\n\n", shared.SanitizeComment(cfg.Name)))

	b.WriteString("services:\n")
	for _, agent := range cfg.Agents {
		agentID := shared.SanitizeID(agent.Name)
		b.WriteString(fmt.Sprintf("  agent-%s:\n", agentID))
		b.WriteString("    image: ghcr.io/openclaw/openclaw:latest\n")
		b.WriteString("    volumes:\n")
		b.WriteString(fmt.Sprintf("      - ./agent-%s/openclaw.json:/home/node/.openclaw/openclaw.json:ro\n", agentID))
		b.WriteString(fmt.Sprintf("      - ./agent-%s/sandbox-policy.yaml:/home/node/.openclaw/sandbox-policy.yaml:ro\n", agentID))
		b.WriteString("      - context-data:/workspace/context\n")

		// Environment variables: passthrough only (no values, no secret leakage)
		envVars := CollectEnvVarNames(cfg)
		if len(envVars) > 0 {
			b.WriteString("    environment:\n")
			for _, envVar := range envVars {
				b.WriteString(fmt.Sprintf("      - %s\n", envVar))
			}
		}

		b.WriteString("    networks:\n")
		b.WriteString("      - internal\n")
	}

	b.WriteString("\nnetworks:\n")
	b.WriteString("  internal:\n")
	b.WriteString("    internal: true\n")

	b.WriteString("\nvolumes:\n")
	b.WriteString("  context-data:\n")

	return b.String()
}

// CollectEnvVarNames extracts environment variable names from provider configs.
// Returns only the names (e.g., "OPENAI_API_KEY"), never resolved values.
func CollectEnvVarNames(cfg *config.Config) []string {
	seen := map[string]bool{}
	var names []string

	for _, pDef := range cfg.Settings.Providers {
		if shared.IsEnvRef(pDef.APIKey) {
			name := pDef.APIKey[2 : len(pDef.APIKey)-1] // extract from ${...}
			if !seen[name] {
				seen[name] = true
				names = append(names, name)
			}
		}
		if shared.IsEnvRef(pDef.BaseURL) {
			name := pDef.BaseURL[2 : len(pDef.BaseURL)-1]
			if !seen[name] {
				seen[name] = true
				names = append(names, name)
			}
		}
	}

	return names
}
