<script setup lang="ts">
import { ref } from 'vue';

const emit = defineEmits<{
  'accepted': [];
}>();

const agreed = ref(false);
</script>

<template>
  <div class="license-overlay">
    <div class="license-card">
      <div class="license-brand">
        <span class="brand-mark">R&gt;</span>
        <span class="brand-name">Rakitsu</span>
      </div>

      <h2 class="license-title">License Agreement</h2>

      <div class="license-body">
        <p>
          Rakitsu is licensed under the
          <strong>Business Source License 1.1 (BSL 1.1)</strong>.
        </p>
        <ul>
          <li>You may use, copy, and modify the source code for non-production purposes.</li>
          <li>Production use requires a commercial license from the licensor.</li>
          <li>After 4 years from each release, the code converts to Apache 2.0.</li>
        </ul>

        <p class="license-disclaimer">
          Agent outputs are generated by third-party LLM providers
          (OpenAI, Anthropic, Google, Ollama, etc.).
          Rakitsu does not collect, store, or transmit your data.
          You are responsible for your use of third-party APIs and
          any data sent to them.
        </p>

        <p class="license-link">
          Full license text:
          <a href="https://github.com/paupawsan/rakitsu/blob/main/LICENSE" target="_blank" rel="noopener">
            LICENSE
          </a>
        </p>
      </div>

      <label class="license-agree">
        <input type="checkbox" v-model="agreed" />
        I have read and agree to the license terms
      </label>

      <button
        class="accept-btn"
        :disabled="!agreed"
        @click="emit('accepted')"
      >
        Continue
      </button>
    </div>
  </div>
</template>

<style scoped>
.license-overlay {
  position: fixed;
  inset: 0;
  z-index: 200;
  background: var(--surface-0);
  display: flex;
  align-items: center;
  justify-content: center;
  overflow-y: auto;
}

.license-card {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 16px;
  padding: 40px 48px;
  margin: 20px;
  background: var(--surface-1);
  border: 1px solid var(--border-default);
  border-radius: var(--node-radius);
  max-width: 520px;
  width: 100%;
}

.license-brand {
  display: flex;
  align-items: baseline;
  gap: 8px;
}
.brand-mark {
  font-family: var(--font-mono);
  font-size: 24px;
  color: var(--accent-agent);
  font-weight: 700;
}
.brand-name {
  font-size: 24px;
  font-weight: 600;
  color: var(--text-primary);
}

.license-title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  color: var(--text-primary);
}

.license-body {
  width: 100%;
  padding: 16px;
  background: var(--surface-2);
  border: 1px solid var(--border-subtle);
  border-radius: var(--node-radius);
  font-size: 13px;
  color: var(--text-secondary);
  line-height: 1.6;
  max-height: 300px;
  overflow-y: auto;
}
.license-body p {
  margin: 0 0 10px;
}
.license-body p:last-child {
  margin-bottom: 0;
}
.license-body ul {
  margin: 0 0 10px;
  padding-left: 20px;
}
.license-body li {
  margin-bottom: 4px;
}
.license-body strong {
  color: var(--text-primary);
}

.license-disclaimer {
  padding: 10px;
  background: var(--surface-3);
  border-radius: var(--node-radius);
  font-size: 12px;
  color: var(--text-muted);
}

.license-link {
  font-size: 12px;
}
.license-link a {
  color: var(--accent-agent);
  text-decoration: none;
}
.license-link a:hover {
  text-decoration: underline;
}

.license-agree {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 13px;
  color: var(--text-secondary);
  cursor: pointer;
  user-select: none;
}
.license-agree input {
  accent-color: var(--accent-agent);
}

.accept-btn {
  width: 100%;
  padding: 10px 20px;
  font-size: 14px;
  font-weight: 600;
  color: #fff;
  background: var(--accent-agent);
  border: none;
  border-radius: var(--node-radius);
  cursor: pointer;
  transition: opacity 0.15s;
}
.accept-btn:hover:not(:disabled) {
  opacity: 0.9;
}
.accept-btn:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}
</style>
